### ISSUE TITLE
xpselect not updating the exposure when cutting between tmin and tmax

### ISSUE THREAD

**Issue by albertomanfreda** [lucabaldini/ixpeobssim#646] opened 2022-10-03 15:14 UTC
When cutting a data file with xpselect specifying a pair of time extrema (i.e. --tmin and --tmax) the LIVETIME keyword in the header of the file stays the same, so that fitting with xspec produces a bogus normalization.

**Comment by lucabaldini** [comment] 2022-11-16 19:24
Duplicate of issue #602

**Closed** 2022-11-16 19:23 UTC
